type SellerType = {
  image: string;
  name: string;
  category: string;
  website: string;
  rating: number;
  reviews: number;
  address: string;
  email: string;
  phone: string;
  product_type: string;
  revenue: number;
  progress: number;
  item_stock: number;
  sells: number;
  happy_clients: number;
};

export const sellerData: SellerType[] = [
  {
    image: 'assets/images/seller/zara.svg',
    name: 'ZARA International',
    category: 'Fashion',
    website: 'www.zarafashion.co',
    rating: 4.5,
    reviews: 3500,
    address: '4604 , Philli Lane Kiowa IN 47404',
    email: 'zarafashionworld@dayrep.com',
    phone: '+243 812-801-9335',
    product_type: 'Fashion',
    revenue: 200000,
    progress: 80,
    item_stock: 865,
    sells: 4500,
    happy_clients: 2000,
  },
  {
    image: 'assets/images/seller/rolex.svg',
    name: 'Rolex Watches',
    category: 'Watch',
    website: 'www.rolexwatch.co',
    rating: 4.5,
    reviews: 1200,
    address: '1678 Avenue Milwaukee, WI 53202',
    email: 'rolexwatches@dayrep.com',
    phone: '+243 262-223-1464',
    product_type: 'Watches',
    revenue: 349000,
    progress: 60,
    item_stock: 261,
    sells: 2900,
    happy_clients: 1400,
  },
  {
    image: 'assets/images/seller/dyson.svg',
    name: 'Dyson Machinery',
    category: 'Electronics',
    website: 'www.dysonmachine.co',
    rating: 4.1,
    reviews: 3700,
    address: '23 Cubbine Road GHOOLI WA 6426',
    email: 'dysonmachine@dayrep.com',
    phone: '+81(08) 9059 8047',
    product_type: 'Electronics',
    revenue: 545000,
    progress: 90,
    item_stock: 781,
    sells: 5300,
    happy_clients: 3100,
  },
  {
    image: 'assets/images/seller/gopro.svg',
    name: 'GoPro Camera',
    category: 'Electronics',
    website: 'www.goprocamera.co',
    rating: 4.3,
    reviews: 7200,
    address: '5 Gaffney Street MIDDLE PARK VIC 3206',
    email: 'goprocamera@dayrep.com',
    phone: '+81(08) 6727 4227',
    product_type: 'Camera',
    revenue: 465000,
    progress: 40,
    item_stock: 890,
    sells: 10600,
    happy_clients: 6300,
  },
  {
    image: 'assets/images/seller/h&m.svg',
    name: 'H&M',
    category: 'Fashion',
    website: 'www.h&mfashion.co',
    rating: 4.3,
    reviews: 15300,
    address: '1697 Bay Street Toronto, ON M5J 2R8',
    email: 'h&mfashion@dayrep.com',
    phone: '+81(07) 4049 2261',
    product_type: 'Fashion',
    revenue: 800000,
    progress: 90,
    item_stock: 1309,
    sells: 21600,
    happy_clients: 8100,
  },
  {
    image: 'assets/images/seller/huawei.svg',
    name: 'Huawei Phone',
    category: 'Electronics',
    website: 'www.huaweiphone.co',
    rating: 4.1,
    reviews: 8200,
    address: '2182 Blanshard Victoria, BC V8W 2H9',
    email: 'huaweiphone@dayrep.com',
    phone: '+81(07) 250-356-8142',
    product_type: 'Phone',
    revenue: 379000,
    progress: 40,
    item_stock: 356,
    sells: 4000,
    happy_clients: 6300,
  },
  {
    image: 'assets/images/seller/nike.svg',
    name: 'Nike Clothings',
    category: 'Fashion',
    website: 'www.nikebrand.co',
    rating: 4.5,
    reviews: 18900,
    address: '2113 Eglinton Avenue Toronto 1A6',
    email: 'nikefashion@dayrep.com',
    phone: '+81(07) 647-405-3676',
    product_type: 'Clothings',
    revenue: 890000,
    progress: 70,
    item_stock: 12000,
    sells: 19000,
    happy_clients: 16000,
  },
  {
    image: 'assets/images/seller/thenorthface.svg',
    name: 'The North Face',
    category: 'Fashion',
    website: 'www.northface.co',
    rating: 4.4,
    reviews: 12700,
    address: '1377 49th Avenue Clyde River,0E0',
    email: 'thenorthface@dayrep.com',
    phone: '+81(07) 867-924-6639',
    product_type: 'Clothings',
    revenue: 457000,
    progress: 30,
    item_stock: 1600,
    sells: 13900,
    happy_clients: 2100,
  },
];
