type CouponType = {
  image: string;
  name: string;
  category: string;
  size?: string;
  price: number;
  discount: number;
  code: string;
  start_date: string;
  end_date: string;
  status: string;
};

export const CouponData: CouponType[] = [
  {
    image: 'assets/images/product/p-1.png',
    name: 'Black T-shirt',
    category: 'Fashion',
    price: 80.0,
    discount: 20.0,
    code: 'FASHION123',
    start_date: '12 May 2023',
    end_date: '12 Jun 2023',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-2.png',
    name: 'Olive Green Leather Bag',
    category: 'Hand Bag',
    price: 136.0,
    discount: 37.0,
    code: 'SUMMER24',
    start_date: '19 July 2023',
    end_date: '23 Aug 2023',
    status: 'Expired',
  },
  {
    image: 'assets/images/product/p-3.png',
    name: 'Women Golden Dress',
    category: 'Fashion',
    price: 219.0,
    discount: 20.0,
    code: 'FASHION123',
    start_date: '24 Aug 2023',
    end_date: '20 Sep 2023',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-4.png',
    name: 'Gray Cap For Men',
    category: 'Cap',
    price: 76.0,
    discount: 12.0,
    code: 'CODE000',
    start_date: '30 Dec 2023',
    end_date: '17 Jan 2024',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-5.png',
    name: 'Dark Green Cargo Pent',
    category: 'Fashion',
    price: 110.0,
    discount: 20.0,
    code: 'FASHION123',
    start_date: '11 Jan 2024',
    end_date: '15 Feb 2024',
    status: 'Expired',
  },
  {
    image: 'assets/images/product/p-6.png',
    name: 'Orange Multi Color Headphone',
    category: 'Electronics',
    price: 231.0,
    discount: 35,
    code: 'HEADPHONE24',
    start_date: '31 May 2023',
    end_date: '23 Jun 2023',
    status: 'Expired',
  },
  {
    image: 'assets/images/product/p-7.png',
    name: "Kid's Yellow Shoes",
    category: 'Foot Wares',
    price: 89.0,
    discount: 19.0,
    code: "KID'S24",
    start_date: '16 May 2024',
    end_date: '12 Jun 2024',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-8.png',
    name: 'Men Dark Brown Wallet',
    category: 'Wallet',
    price: 132.0,
    discount: 50,
    code: 'BRAND24',
    start_date: '25 Jan 2024',
    end_date: '16 Feb 2024',
    status: 'Expired',
  },
  {
    image: 'assets/images/product/p-9.png',
    name: 'Sky Blue Sunglass',
    category: 'Sunglass',
    price: 77.0,
    discount: 23.0,
    code: 'EYEWARE24',
    start_date: '23 Feb 2024',
    end_date: '24 March 2024',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-10.png',
    name: "Kid's Yellow T-shirt",
    category: 'Fashion',
    price: 110.0,
    discount: 35.0,
    code: "KID'S24",
    start_date: '14 Aug 2023',
    end_date: '15 Sep 2023',
    status: 'Active',
  },
  {
    image: 'assets/images/product/p-11.png',
    name: 'White Rubber Band Smart Watch',
    category: 'Electronics',
    price: 77.0,
    discount: 14.0,
    code: 'WATCH2W1',
    start_date: '27 March 2024',
    end_date: '12 Apr 2024',
    status: 'Expired',
  },
  {
    image: 'assets/images/product/p-12.png',
    name: 'Men Brown Leather Shoes',
    category: 'Footware',
    size: "40 , 41 , 42 , 43",
    price: 222.0,
    discount: 40,
    code: 'FOOTWARE23',
    start_date: '23 Dec 2023',
    end_date: '22 Jan 2024',
    status: 'Active',
  },
];
